### ISSUE TITLE
I am trying to figure out how to best change the various font attributes

### ISSUE THREAD

**Issue by mikeerickson** [gregoriohc/laravel-nova-theme-classify#4]
For example, I want to change the font-size to something smaller as the current 16px is quite large for me on my 13" screen.

How would I got about this using your package?

I can see there is major upside to using this package.

**Comment by mikeerickson** [comment]
I was able to accomplish what I wanted by doing the following.  There are some other places that I want to customize, but this touched most of the UI that I want to have smaller

Thanks a bunch for this package, got me to where I wanted to be quick once I figured out how it worked.

```css

/*
    Override base font sizze (was too big at 16px) 
 */

body, table, td, th, ul, li, a, span.sidebar-label {
    font-size: 13px;
}

```
